- 1.1.14
- _NAME: 'MX Ergo Multi-Device Trackball '
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode,
    onboard_profiles, report_rate, report_rate_extended, dpi, dpi_extended, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in,
    backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting, fn-swap, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, gesture2-gestures, gesture2-divert, gesture2-params, sidetone, equalizer,
    adc_power_management]
  _battery: 4096
  _modelId: B01D406F0000
  _sensitive: {change-host: false, divert-keys: false, lowres-scroll-mode: false, persistent-remappable-keys: false, pointer_speed: false, reprogrammable-keys: true,
    speed-change: false}
  _speed-change: 511
  _unitId: A71898E9
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 91: 0, 93: 0, 237: 0}
  lowres-scroll-mode: false
  persistent-remappable-keys: null
  pointer_speed: 511
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 91: 91, 93: 93, 237: 237}
  speed-change: 0
